### PR TITLE
Keep all intermediate exceptions to provide call traces

### PR DESCRIPTION
**Pull request by raymcdermott**

### CODE REVIEW

**Comment by raymcdermott** [comment]
I don't know if this is abandonware but we found it useful. 
The PR adds one feature to retain intermediate stack traces.
We also want to use it with `deps.edn` via git SHAs rather than a central repo

**Comment by moea** [comment]
I'm no longer actively using it, but I'm happy to merge and release.

**Comment by raymcdermott** [comment]
Great - thanks.

Have you found something better or is there another reason you no longer
use it?

**Comment by moea** [comment]
I switched to using promises (e.g. promesa) for single deferred values, and
if I'm using core.async as intended - for dataflows - I may use separate
error channels, depending on the use case.  That said, I don't think there
is anything fundamentally wrong with the primitives in this library, and
there are definitely circumstances where I'd reach for it.

**Pull request closed without merging**
